version: '3.8'
services:
  svtrain-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-builder
    command: sh -c "node --inspect=0.0.0.0 server.js"
    working_dir: /app/api
    env_file:
      - development.env
    ports:
      - "9229:9229"
    expose:
      - "3333"
    volumes:
      - ./api:/app/api:cached
      - /app/api/node_modules
      - ./api/development:/app/api/development

  svtrain-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-builder
    command: sh -c "yarn run serve --host 0.0.0.0 --port 8080"
    working_dir: /app/ui
    environment:
      - NODE_ENV=development
      - GITHUB_SHA=localdev
      - GITHUB_REPOSITORY=com2u/SVTrain
    expose:
      - "8080"
    volumes:
      - ./ui:/app/ui:cached
      - /app/ui/node_modules

  svtrain-nginx:
    image: nginx:latest
    ports:
      - "3333:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
