#!/usr/bin/env node
const fs = require('fs')
const passwordHash = require('password-hash')
const path = require('path')

const user = {
  login: null,
  password: null,
  passwordHash: null
}

const iteration = () => {
  if (user.login === null) {
    process.stdout.write('Login: ')
    return;
  } else if (user.password === null ) {
    process.stdout.write('Password: ')
    return;
  }

  let users = {}
  if (!fs.existsSync(path.join(__dirname, 'users.json'))) {
    users = {}
  } else {
    users = JSON.parse(fs.readFileSync(path.join(__dirname, 'users.json')))
  }

  user.passwordHash = passwordHash.generate(user.password)
  if (users[user.login]) {
    users[user.login].passwordHash = user.passwordHash
  } else {
    users[user.login] = {
      login: user.login,
      passwordHash: user.passwordHash
    }
  }
  fs.writeFileSync('./users.json', JSON.stringify(users, null, 4))
  process.stdout.write(`Settings for user ${user.login} are saved!\n`)
  process.exit(0)
}

process.stdin.on('data', (data) => {
  const dataString = data.toString().replace('\n', '').replace('\r', '')
  if (user.login === null) {
    user.login = dataString
  } else if (user.password === null) {
    user.password = dataString
  }
  iteration()
})

iteration()